/*
 * ALISI client
 *
 * This is the client API of ALISI. Each device will expose this API in order to be identified by ALISI compliant control units.
 *
 * API version: 1.0.0
 * Contact: matteo.sovilla@studenti.unipd.it
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"github.com/TeoSocs/alisi-client/crypto"
	"github.com/op/go-logging"
	"net/http"

	sw "github.com/TeoSocs/alisi-client/swagger"
)

func main() {

	var log = logging.MustGetLogger("alisi")

	crypto.TEST_ENV = true
	crypto.Init()

	log.Info("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
