/*
 * ALISI client
 *
 * This is the client API of ALISI. Each device will expose this API in order to be identified by ALISI compliant control units.
 *
 * API version: 1.0.0
 * Contact: matteo.sovilla@studenti.unipd.it
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"github.com/TeoSocs/alisi-client/crypto"
	"net/http"
)

func GetPublicKey(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	publicKey, err := crypto.GetPublicKey()
	if err != nil {
		log.Errorf("error retrieving public key: %v", err)
		http.Error(w, "error retrieving public key", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
	_, err = w.Write([]byte(crypto.EncodePublicKeyToPem(publicKey)))
	if err != nil {
		log.Errorf("error encoding pubKey: %v", err)
	}
}
