/*
 * ALISI client
 *
 * This is the client API of ALISI. Each device will expose this API in order to be identified by ALISI compliant control units.
 *
 * API version: 1.0.0
 * Contact: matteo.sovilla@studenti.unipd.it
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/alisi/v1/",
		Index,
	},

	Route{
		"CreateClaim",
		strings.ToUpper("Post"),
		"/alisi/v1/claim",
		CreateClaim,
	},

	Route{
		"DeleteClaim",
		strings.ToUpper("Delete"),
		"/alisi/v1/claim/{claimID}",
		DeleteClaim,
	},

	Route{
		"GetClaimByID",
		strings.ToUpper("Get"),
		"/alisi/v1/claim/{claimID}",
		GetClaimByID,
	},

	Route{
		"GetClaimList",
		strings.ToUpper("Get"),
		"/alisi/v1/claim",
		GetClaimList,
	},

	Route{
		"RequestSigned",
		strings.ToUpper("Post"),
		"/alisi/v1/claim/{claimID}/request_signed/{nonce}",
		RequestSigned,
	},

	Route{
		"GetPublicKey",
		strings.ToUpper("Get"),
		"/alisi/v1/public_key",
		GetPublicKey,
	},
}
